# Generated by Django 5.2.1 on 2025-05-28 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_image', models.CharField(max_length=255)),
                ('ram_required', models.IntegerField()),
                ('cpu_required', models.IntegerField()),
                ('gpu_required', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(default='queued', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='cluster.cluster')),
            ],
        ),
    ]
