# Generated by Django 5.2.1 on 2025-05-28 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ram', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('gpu', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_ram', models.IntegerField(default=0)),
                ('allocated_cpu', models.IntegerField(default=0)),
                ('allocated_gpu', models.IntegerField(default=0)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='cluster.cluster')),
            ],
        ),
    ]
